### ISSUE TITLE
Enable sourcemaps?

### ISSUE THREAD

**Issue by stevage** [gridonic/web-boilerplate#3]
Hi, this is great! It doesn't seem to generate any sourcemaps, though. Is there a flag I need to set in `project.json` to pass to browersify maybe?

**Comment by mzdr** [comment]
Hey Steve! 

You were right! There was no way to enable source maps, but I fixed it and just released a [new version](https://github.com/gridonic/web-boilerplate/releases/latest) (2.0.3). With that version you now can specify the `browserify` settings within the `scripts` key in the `project.json`. 

For example:

```javascript
"scripts": {
    // …
    "browserify": {
        "debug": true // When true, add a source map inline to the end of the bundle.
    },
    "babelify": {
        "presets": ["babel-preset-es2015"]
    }
}
```

Further information especially in conjunction with babel(ify):

[Browserify Options](https://github.com/substack/node-browserify#browserifyfiles--opts)
[Why am I not getting source maps?](https://github.com/babel/babelify#why-am-i-not-getting-source-maps)

**Comment by stevage** [comment]
Perfect, that works!
